# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deleting.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(180, 105)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        self.buttonDelete = QtWidgets.QPushButton(Form)
        self.buttonDelete.setGeometry(QtCore.QRect(10, 70, 161, 28))
        self.buttonDelete.setObjectName("buttonDelete")
        self.comboAttribute = QtWidgets.QComboBox(Form)
        self.comboAttribute.setGeometry(QtCore.QRect(10, 10, 161, 22))
        self.comboAttribute.setObjectName("comboAttribute")
        self.lineInput = QtWidgets.QLineEdit(Form)
        self.lineInput.setGeometry(QtCore.QRect(10, 40, 161, 21))
        self.lineInput.setObjectName("lineInput")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Видалення"))
        self.buttonDelete.setText(_translate("Form", "Видалити"))
