# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deleting.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(298, 118)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.comboAttribute = QtWidgets.QComboBox(Form)
        self.comboAttribute.setObjectName("comboAttribute")
        self.gridLayout.addWidget(self.comboAttribute, 0, 0, 1, 1)
        self.lineInput = QtWidgets.QLineEdit(Form)
        self.lineInput.setObjectName("lineInput")
        self.gridLayout.addWidget(self.lineInput, 1, 0, 1, 1)
        self.buttonDelete = QtWidgets.QPushButton(Form)
        self.buttonDelete.setObjectName("buttonDelete")
        self.gridLayout.addWidget(self.buttonDelete, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Видалення"))
        self.buttonDelete.setText(_translate("Form", "Видалити"))
