# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editing.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(718, 251)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonApply = QtWidgets.QPushButton(Form)
        self.buttonApply.setObjectName("buttonApply")
        self.gridLayout.addWidget(self.buttonApply, 0, 0, 1, 1)
        self.buttonEdit = QtWidgets.QPushButton(Form)
        self.buttonEdit.setObjectName("buttonEdit")
        self.gridLayout.addWidget(self.buttonEdit, 0, 1, 1, 1)
        self.spinID = QtWidgets.QSpinBox(Form)
        self.spinID.setObjectName("spinID")
        self.gridLayout.addWidget(self.spinID, 0, 2, 1, 1)
        self.table = QtWidgets.QTableWidget(Form)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.gridLayout.addWidget(self.table, 1, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Редагування"))
        self.buttonApply.setText(_translate("Form", "Застосувати"))
        self.buttonEdit.setText(_translate("Form", "Редагувати поле"))
