# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(309, 250)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonSubmit = QtWidgets.QPushButton(Form)
        self.buttonSubmit.setObjectName("buttonSubmit")
        self.gridLayout.addWidget(self.buttonSubmit, 0, 0, 1, 1)
        self.buttonClean = QtWidgets.QPushButton(Form)
        self.buttonClean.setObjectName("buttonClean")
        self.gridLayout.addWidget(self.buttonClean, 0, 1, 1, 1)
        self.tableFields = QtWidgets.QTableWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableFields.setFont(font)
        self.tableFields.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableFields.setObjectName("tableFields")
        self.tableFields.setColumnCount(2)
        self.tableFields.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableFields.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFields.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.tableFields, 1, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.buttonSubmit.setText(_translate("Form", "Встановити"))
        self.buttonClean.setText(_translate("Form", "Очистити фільтр"))
        item = self.tableFields.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Назви полів"))
        item = self.tableFields.horizontalHeaderItem(1)
        item.setText(_translate("Form", "+/-"))
