# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table_choose_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(770, 347)
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(10, 40, 751, 301))
        self.tableView.setObjectName("tableView")
        self.showTableProviders = QtWidgets.QPushButton(Form)
        self.showTableProviders.setGeometry(QtCore.QRect(160, 10, 151, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.showTableProviders.setFont(font)
        self.showTableProviders.setObjectName("showTableProviders")
        self.showTableWarehouses = QtWidgets.QPushButton(Form)
        self.showTableWarehouses.setGeometry(QtCore.QRect(610, 10, 151, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.showTableWarehouses.setFont(font)
        self.showTableWarehouses.setObjectName("showTableWarehouses")
        self.showTableContracts = QtWidgets.QPushButton(Form)
        self.showTableContracts.setGeometry(QtCore.QRect(460, 10, 151, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.showTableContracts.setFont(font)
        self.showTableContracts.setObjectName("showTableContracts")
        self.showTableApplications = QtWidgets.QPushButton(Form)
        self.showTableApplications.setGeometry(QtCore.QRect(310, 10, 151, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.showTableApplications.setFont(font)
        self.showTableApplications.setObjectName("showTableApplications")
        self.showTableAutos = QtWidgets.QPushButton(Form)
        self.showTableAutos.setGeometry(QtCore.QRect(10, 10, 151, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.showTableAutos.setFont(font)
        self.showTableAutos.setObjectName("showTableAutos")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.showTableProviders.setText(_translate("Form", "Постачальники"))
        self.showTableWarehouses.setText(_translate("Form", "Склади"))
        self.showTableContracts.setText(_translate("Form", "Договори"))
        self.showTableApplications.setText(_translate("Form", "Замовлення"))
        self.showTableAutos.setText(_translate("Form", "Автомобілі"))
